### PR TITLE
Update zodbupdate to work with latest Python versions, and add a conversion feature to Python 3

### PR DESCRIPTION
**Pull request by thefunny42**
We worked to migrate our Zope application to Python 3, keeping our database. We updated zodbupdate to do the conversion of our databases from Python 2 to Python 3, with success.

Additionally, I kind of wrote zodbupdate, and would like to get back write access to it so I can make a release after merging this pull request. But of course review is welcome.

### CODE REVIEW

**Comment by icemac** [comment]
@thefunny42 I adjusted the configuration for this repos. You should now be able to write to aka merge this PR. (Sorry I did not yet have the time to look into it.)

**Review by janjaapdriessen — APPROVED** [review]

**Comment by thefunny42** [comment]
@icemac Is it possible to enable travis for zodbupdate?

**Comment by icemac** [comment]
@thefunny42 Done, enabled TravisCI.

**Comment by icemac** [comment]
@thefunny42 👍 Thank you a lot for your work on this PR. I am sure it will push us a lot further in the Python 3 migration of ZODB based application.

**Comment by thefunny42** [comment]
Thanks. We actually used that script to migrate with success our database to Python 3. We did mostly store unicode already so that was not a big problem.

Additionally we use RelStorage, in history free mode, so we wrote an another script that directly go and update the pickles in the database, using multiple processes to lower the migration time. For a small database of 3G we managed to lower the running time from 2 hours to 10 minutes by doing so.

We will work to open source those as well.

**Comment by icemac** [comment]
@thefunny42 Cool! That's good news!

**Pull request merged**
