### PR TITLE
Fixed incompatibility with ZODB 5.6.

### LINKED ISSUE #35: AttributeError: 'Transaction' object has no attribute 'extension_bytes' [was: Tests in TravisCI are broken]
All jobs besides the `OLDZODB` one are broken, e. g. https://travis-ci.org/github/zopefoundation/zodbupdate/jobs/701272511

There are multiple test failures which all look like this:

```python
Traceback (most recent call last):
264  File "/opt/python/3.8.0/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
265    yield
266  File "/opt/python/3.8.0/lib/python3.8/unittest/case.py", line 676, in run
267    self._callTestMethod(testMethod)
268  File "/opt/python/3.8.0/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
269    method()
270  File "/home/travis/build/zopefoundation/zodbupdate/src/zodbupdate/tests.py", line 871, in test_convert_attribute_to_bytes
271    self.update(convert_py3=True, default_decoders={
272  File "/home/travis/build/zopefoundation/zodbupdate/src/zodbupdate/tests.py", line 168, in update
273    updater()
274  File "/home/travis/build/zopefoundation/zodbupdate/src/zodbupdate/update.py", line 78, in __call__
275    t = self.__new_transaction()
276  File "/home/travis/build/zopefoundation/zodbupdate/src/zodbupdate/update.py", line 59, in __new_transaction
277    self.storage.tpc_begin(t)
278  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/ZODB/BaseStorage.py", line 193, in tpc_begin
279    ext = transaction.extension_bytes
280AttributeError: 'Transaction' object has no attribute 'extension_bytes'
```

Do we use a too new or too old version of `transaction`?
The tests break locally in the same way.
There is even no `extension_bytes` in the `transaction` package.
Am I missing something here?

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/zopefoundation/zodbupdate/issues/35
This applies the fix from https://github.com/zopefoundation/zodbupdate/issues/35#issuecomment-663530603

### CODE REVIEW

**Review by jamadden — COMMENTED** [review]
I don't know much about the internals of `zodbupdate`, but (a) this is providing the interface that storages expect and (b) fixes the tests on CI. So I guess it's good?

**Review by dataflake — APPROVED** [review]
LGTM - but as I said on the issue, I don't have the depth of knowledge to really judge the impact.

**Comment by mauritsvanrees** [comment]
It works for me, both on Python 2.7 and 3.7. Sites seem fine afterwards.

@thefunny42 You wrote most of zodbupdate, so maybe you can comment?
Otherwise I am inclined to merge.

**Comment by mauritsvanrees** [comment]
I have merged.

Now we could use a new release.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zodbupdate/1.5/.

**Pull request merged**
